//Pipeline by Amir@Mindef v1.00

pipeline {
    agent {
        label 'jenkins-linux-agent-TLS'
    }
    
    environment {
        HARBOR_REGISTRY = 'bakul.mod.gov.my'  // Harbor registry URL
        HARBOR_PROJECT = 'testing-app'  // Harbor project where image will be pushed
        HARBOR_IMAGE = 'myrepository' //nama repositori
        IMAGE_NAME_HARBOR = "${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${HARBOR_IMAGE}"  // Full image name for Harbor
        TAG = 'v1.7'  // Tag for the Docker image
        DOCKERFILE_LOCATION = './Dockerfile'     // Dockerfile in root location './tot/lab-01/Dockerfile'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your repository 
                git branch: 'main', url: "https://github.com/usyarni-cell/lab2.git"
            }
        }
        
        stage('Check Dockerfile Location') {
            steps {
                script {
                    // Check if the Dockerfile exists in the root location
                    if (fileExists(DOCKERFILE_LOCATION)) {
                        echo "Dockerfile found at ${DOCKERFILE_LOCATION}"
                    } else {
                        error "Dockerfile not found at ${DOCKERFILE_LOCATION}"
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image using docker.build with --no-cache option
                    docker.build("${IMAGE_NAME_HARBOR}:${TAG}", "--no-cache -f ${DOCKERFILE_LOCATION} .")
                }
            }
        }

        stage('Tag and Push Docker Image to Harbor') {
            steps {
                script {
                    // Use docker.withRegistry for secure login and push to Harbor
                    docker.withRegistry("https://${HARBOR_REGISTRY}", 'bakul-testing-app') {
                        docker.image("${IMAGE_NAME_HARBOR}:${TAG}").push()
                    }
                }
            }
        }

        stage('Clean up') {
            steps {
                script {
                    // Remove unused Docker images to free up space
                    sh "docker rmi ${IMAGE_NAME_HARBOR}:${TAG}"
                }
            }
        }
    }

    post {
        always {
            // Clean up workspace after the pipeline
            cleanWs()
        }
    }
}
